# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Amsterdam"
