name: Docker Build and Publish

on:
  schedule:
    - cron: "8 17 * * *"
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

env:
  # <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to DockerHub and Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v5

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      # https://github.com/peter-evans/dockerhub-description
#      - name: Update Docker Hub Description
#        if: github.event_name != 'pull_request'
#        uses: peter-evans/dockerhub-description@v4
#        with:
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          repository: ${{ env.IMAGE_NAME }}
#          short-description: "My custom Caddy builds"

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
