name: Docker Build and Publish

on:
  schedule:
    - cron: "8 17 * * *"
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  # ghcr.io/<account>/<repo>
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v5

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build image for ${{ matrix.arch }}
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE }}:${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,scope=${{ matrix.arch }},mode=max

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}

  manifest:
    name: Create and Push Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create "${IMAGE}:latest" \
            "${IMAGE}:amd64" \
            "${IMAGE}:arm64"
          docker manifest push "${IMAGE}:latest"
